### PR TITLE
Add generic domain docroot under `$HOME`

### PR DESCRIPTION
**Pull request by SKevo18**
Not sure if this is the right way to do it, but the idea is that it would match all folders in `$HOME` with format `domain.tld`

https://www.pivotaltracker.com/n/projects/2320827/stories/187053834

### CODE REVIEW

**Comment by gwillem** [comment]
Good, it can't hurt to check a couple paths extra. Did you check if the trailing slash is a problem elsewhere?

**Comment by SKevo18** [comment]
> Did you check if the trailing slash is a problem elsewhere?

No, but will do... I think that you assume it would cause issues when we join two paths together (double slash) or if `.glob()` would treat it as globbing each folder inside the folder recursively

**Comment by gwillem** [comment]
> you assume it would cause issues when we join two paths together

Well I don't assume, but it can't hurt to check, since this is the only entry with a trailing slash

**Comment by SKevo18** [comment]
Ah so the trailing slash apparently mustn't be there in order for glob to work properly...
Should we safe-guard the paths found by glob by a check if it's a directory? Currently, the tests pass, but maybe we should make sure it doesn't try to access a file as `$DOCROOT`?

**Comment by gwillem** [comment]
I think that safeguard already happens here > https://github.com/sansecio/gocommerce/blob/main/store.go#L97

Great to have another test! Let's go

**Pull request merged**
